datasets:

  ACM:
    num_iters: 400
    dataset: ACM
    sparse: true
    patience: 20
    gpu_num: 1
    seed: 0
    feature_drop: 0.1
    c_dim: 8
    p_dim: 8
    lr_causal: 1.0e-2
    lr_ED: 1.0e-4
    weight_decay_causal: 1.0e-4
    weight_decay_ED: 0
    inner_epochs: 5
    hid_units: 256
    self_sup_coeff: 0.5
    causal_coeff: 0.5
    num_view: 2
    n_augment: 20
    seed_test: 10
    matching_coeff: 1
    noise_std: 0.1
    n_keep_nodes: 0.6
    epochs_evaluation: 400
    lr_evaluation: 0.1
    path: ./data/acm.mat

  IMDB:
    num_iters: 400
    dataset: IMDB
    sparse: true
    patience: 20
    gpu_num: 1
    seed: 0
    feature_drop: 0.1
    c_dim: 8
    p_dim: 8
    lr_causal: 1.0e-2
    lr_ED: 1.0e-4
    weight_decay_causal: 1.0e-4
    weight_decay_ED: 0
    inner_epochs: 5
    hid_units: 256
    self_sup_coeff: 0.1
    causal_coeff: 0.01
    num_view: 2
    n_augment: 20
    seed_test: 10
    matching_coeff: 1
    noise_std: 0.1
    n_keep_nodes: 0.6
    epochs_evaluation: 400
    lr_evaluation: 0.1
    path: ./data/imdb.pkl

  freebase:
    num_iters: 400
    dataset: freebase
    sparse: true
    patience: 20
    gpu_num: 1
    seed: 10
    feature_drop: 0.1
    c_dim: 8
    p_dim: 8
    lr_causal: 1.0e-2
    lr_ED: 1.0e-4
    weight_decay_causal: 1.0e-4
    weight_decay_ED: 0
    inner_epochs: 5
    hid_units: 512
    self_sup_coeff: 0.1
    causal_coeff: 0.01
    num_view: 3
    n_augment: 30
    seed_test: 10
    matching_coeff: 1
    noise_std: 0.1
    n_keep_nodes: 0.6
    epochs_evaluation: 400
    lr_evaluation: 0.1
    path: data/freebase/

  DBLP:
    num_iters: 400
    dataset: DBLP
    sparse: true
    patience: 20
    gpu_num: 1
    seed: 0
    feature_drop: 0.1
    c_dim: 8
    p_dim: 8
    lr_causal: 1.0e-2
    lr_ED: 1.0e-4
    weight_decay_causal: 1.0e-4
    weight_decay_ED: 0
    inner_epochs: 5
    hid_units: 256
    self_sup_coeff: 0.05
    causal_coeff: 0.05
    num_view: 3
    n_augment: 20
    seed_test: 10
    matching_coeff: 1
    noise_std: 0.1
    n_keep_nodes: 0.6
    epochs_evaluation: 400
    lr_evaluation: 0.1
    path: data/dblp.pkl

  Syn1:
    num_iters: 140
    dataset: Syn1
    sparse: true
    patience: 20
    gpu_num: -1
    seed: 15
    feature_drop: 0.1
    c_dim: 8
    p_dim: 8
    lr_causal: 1.0e-2
    lr_ED: 1.0e-4
    weight_decay_causal: 1.0e-4
    weight_decay_ED: 0
    inner_epochs: 15
    hid_units: 256
    self_sup_coeff: 1.5
    causal_coeff: 3.4
    num_view: 3
    n_augment: 5
    seed_test: 1
    matching_coeff: 0.9
    noise_std: 0.1
    n_keep_nodes: 0.6
    epochs_evaluation: 50
    lr_evaluation: 0.3
    n_nodes: 100
    n_communities: 3
    p_intra: 0.7
    p_inter: 0.1
    label_probs: [0.8, 0.1, 0.1]

  Syn2:
    num_iters: 200
    dataset: Syn2
    sparse: true
    patience: 20
    gpu_num: 1
    seed: 0
    feature_drop: 0.1
    c_dim: 8
    p_dim: 8
    lr_causal: 1.0e-2
    lr_ED: 1.0e-4
    weight_decay_causal: 1.0e-4
    weight_decay_ED: 0
    inner_epochs: 5
    hid_units: 256
    self_sup_coeff: 0.5
    causal_coeff: 0.5
    num_view: 3
    n_augment: 20
    matching_coeff: 1
    noise_std: 0.1
    n_keep_nodes: 0.6
    n_node: 1000
    portion: 0.5
    pin: 0.3
    pout: 0.01
    pin_priv: 0.3
    pout_priv: 0.01
    n_communities: 3

  Syn3:
    num_iters: 200
    dataset: Syn3
    sparse: true
    patience: 20
    gpu_num: 1
    seed: 0
    feature_drop: 0.1
    c_dim: 8
    p_dim: 8
    lr_causal: 1.0e-2
    lr_ED: 1.0e-4
    weight_decay_causal: 1.0e-4
    weight_decay_ED: 0
    inner_epochs: 5
    hid_units: 256
    self_sup_coeff: 0.05
    causal_coeff: 0.05
    num_view: 2
    n_augment: 20
    matching_coeff: 1
    noise_std: 0.1
    n_keep_nodes: 0.6
    n_node: 600
    n_neighbors: 14
    n_communities: 3
    alpha_h: 1.0
    snr_common: 0.8
    snr_private: 1.0

  Syn4:
    num_iters: 200
    dataset: Syn4
    sparse: true
    patience: 20
    gpu_num: 1
    seed: 0
    feature_drop: 0.1
    c_dim: 8
    p_dim: 8
    lr_causal: 1.0e-2
    lr_ED: 1.0e-4
    weight_decay_causal: 1.0e-4
    weight_decay_ED: 0
    inner_epochs: 5
    hid_units: 256
    self_sup_coeff: 0.5
    causal_coeff: 0.5
    num_view: 2
    n_augment: 20
    seed_test: 10
    matching_coeff: 1
    noise_std: 0.1
    n_keep_nodes: 0.6
    epochs_evaluation: 400
    lr_evaluation: 0.1
    n_node: 100
    p_edge: 0.08
    n_structures: 30


  